### ISSUE TITLE
Input Method: iBus is not selected / active out of the box

### ISSUE THREAD

**Issue by Hacime** [elementary/switchboard-plug-keyboard#327]
After a fresh install when other input methods are added the settings don't work because iBus is not active / configured.
I had to run "sudo im-config" and select iBus. Then it worked fine.

Can this be configured / selected out of the box?
I had to search online until I found how to make the input methods work.
Would be more convenient if it works out of the box.

OS version 5.1.7

**Comment by ryonakano** [comment]
Yeah, I do also think it should be active by default like Ubuntu or other distros. However, It would be an issue of the base system like os-patches rather than this plug. Also, it's already reported at https://github.com/elementary/os/issues/103, so I'll close this issue. Anyway, thank you for your reporting and contributing l10n improvement of elementary OS :)
