### ISSUE TITLE
Cannot use alt+shift accelerator when assigning shortcuts

### ISSUE THREAD

**Issue by Kethen** [elementary/switchboard-plug-keyboard#387]
## What Happened
cannot create keyboard shortcuts with alt+shirt+any key

## Expected Behavior
much like switch to previous window key, alt+shirt+tab is the default shortcut (interestingly that doesn't work but that's not the scope of this bug report), so alt+shift+any key should be allowed

## Steps to Reproduce

1. select an item to assign a shortcut
2. hit alt, then shift, then number 1 for example
3. alt+1 is assigned

alternatively

1. select an item to assign a shortcut
2. hit shift, then alt, then number 1 for example
3. shift+! is assigned

## Workaround
alt+shift seems to be occupied by switching keyboard layout by default, disable keyboard layout switching then re-login fixes the issue

## Platform Information
elementary OS 6 Odin

**Comment by jeremypw** [comment]
This looks equivalent to #270 where I suggested the same work around.

**Comment by jeremypw** [comment]
I wonder whether Gala could be patched so that if there is only one keyboard layout then `Alt + Shift` is not intercepted?  Need to check whether there is an issue outstanding on Gala.

**Comment by rgbmew** [comment]
Having a similar problem, although with a Super+Shift, instead of Alt+Shift. I'm trying to set my screenshot hotkey to Shift+Super+4, and it doesn't work at all. Shift+4 and Super+4 both work on their own, but I can't get Super+Shift+4, specifically, working. It's been a huge pain in my butt recently, I use a mechanical Mac keyboard, and instead of the Printscreen button being the literal Printscreen input, it's the Mac Printscreen shortcut, Command+Shift+4.
Side note; I also think it's sort of odd how mapping a shortcut with Shift will also map the other key as being Shifted. For example, the Shift+4 hotkey will map as Shift+$. Not really a "problem," just sort of distracting.

**Comment by lenemter** [comment]
Closing in favor of https://github.com/elementary/gala/issues/1261.
